import logging
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from app.github.client import RepoHealGitHubClient
from app.github.changes_branch import ChangesBranchManager
from app.remediation.engine import RemediationEngine
from app.models.migration_models import HealthReport
from app.github.metadata_branch import MetadataBranchManager

logger = logging.getLogger(__name__)

class RemediationPipeline:
    def __init__(self, github_client: RepoHealGitHubClient):
        self.github_client = github_client
        self.branch_manager = ChangesBranchManager(github_client)
        self.metadata_manager = MetadataBranchManager(github_client)

    async def run_remediation(
        self,
        repo_id: str,
        analysis_id: str,
        migration_id: str,
        patches: List[Dict[str, Any]],
        draft: bool = False
    ):
        """Apply patches and create PR (optional draft)."""
        repo = self.github_client.get_repo(repo_id)
        default_branch = repo.default_branch
        
        # 1. Apply patches
        modified_files = {}
        for file_path, file_patches in self._group_patches(patches).items():
            try:
                content = repo.get_contents(file_path, ref=default_branch).decoded_content.decode("utf-8")
                engine = RemediationEngine(content)
                for p in file_patches:
                    self._apply_patch(engine, p)
                if engine.modified and engine.validate():
                    modified_files[file_path] = engine.get_modified_source()
            except Exception as e:
                logger.error(f"Patch error {file_path}: {e}")

        if not modified_files: return None

        # 2. Extract library info from patches for title
        lib_name = migration_id.replace("mig_", "").split("_")[0] if migration_id.startswith("mig_") else migration_id
        old_ver = ""
        new_ver = ""
        for p in patches:
            if p.get("type") == "import_rewrite":
                old_mod = p.get("old", "")
                new_mod = p.get("new", "")
                lib_parts = old_mod.split(".")[0] if old_mod else ""
                if lib_parts:
                    lib_name = lib_parts
                    break
        title = f"[RepoHeal] Migrate {lib_name}"
        if old_ver and new_ver:
            title += f" {old_ver} → {new_ver}"

        # 3. Branch & Commit
        branch_name = self.branch_manager.create_changes_branch(repo, migration_id)
        self.branch_manager.batch_commit_changes(repo, branch_name, modified_files, f"RepoHeal: {migration_id}")
        
        # 4. PR Body
        report_url = f"/reports/{repo_id}/health-page?analysis_id={analysis_id}"
        mig_url = f"/reports/{repo_id}/migration-page?analysis_id={analysis_id}"
        symbols_changed = [p.get("old", p.get("func", "unknown")) for p in patches]
        
        body = f"""## [RepoHeal] Automated Remediation
This PR was generated to address issues identified in analysis `{analysis_id}`.

### Details
- **Migration ID**: `{migration_id}`
- **Risk Score**: {getattr(patches[0], 'risk_score', 'N/A') if patches else 'N/A'}
- **Files Changed**: {len(modified_files)}
- **Symbols Changed**: {', '.join(symbols_changed[:10])}{'...' if len(symbols_changed) > 10 else ''}
- **Health Report**: [View Report]({report_url})
- **Migration Document**: [View Document]({mig_url})

### Evidence
- Patches applied: {len(patches)}
- Files modified: {', '.join(modified_files.keys())}

---
*Generated by RepoHeal*
"""
        
        # 5. Create PR
        pr = repo.create_pull(
            title=title,
            body=body,
            base=default_branch,
            head=branch_name,
            draft=draft
        )
        
        # 6. Save PR Metadata with state history
        now_iso = datetime.now(timezone.utc).isoformat()
        commit_sha = repo.get_branch(branch_name).commit.sha
        pr_metadata = {
            "analysis_id": analysis_id,
            "migration_id": migration_id,
            "repository_snapshot_id": analysis_id,
            "commit_sha": commit_sha,
            "branch": branch_name,
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "changes_branch": branch_name,
            "created_at": now_iso,
            "status": "draft" if draft else "created",
            "is_draft": draft,
            "state_history": [
                {"status": "draft" if draft else "created", "timestamp": now_iso}
            ]
        }
        self._save_pr_metadata(repo, pr_metadata)
        return pr

    def _group_patches(self, patches):
        res = {}
        for p in patches: res.setdefault(p["file_path"], []).append(p)
        return res

    def _apply_patch(self, engine, patch):
        t = patch["type"]
        if t == "import_rewrite": engine.rewrite_import(patch["old"], patch["new"])
        elif t == "symbol_rename": engine.rename_symbol(patch["old"], patch["new"])
        elif t == "signature_update": engine.update_api_signature(patch["func"], patch["kwargs"])

    def _save_pr_metadata(self, repo, pr_metadata: Dict[str, Any]):
        manifest = self.metadata_manager._load_manifest(repo)
        manifest.setdefault("pull_requests", [])
        manifest["pull_requests"].append(pr_metadata)
        
        pr_path = f"repoheal.meta/prs/pr_{pr_metadata['pr_number']}.json"
        files = {
            "repoheal.meta/metadata.json": self.metadata_manager._json(manifest),
            pr_path: self.metadata_manager._json(pr_metadata)
        }
        self.github_client.batch_upsert_files(repo, self.metadata_manager.branch_name, files, f"Track PR #{pr_metadata['pr_number']}")
