import httpx
from typing import Any

from app.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)


def send_digest_email(
    to_email: str,
    repository: str,
    digest: dict[str, Any],
) -> bool:
    if not settings.EMAIL_ENABLED:
        logger.info(f"Email disabled, skipping digest for {repository}")
        return False

    subject = f"RepoHeal Weekly Digest â€” {repository}"
    html = _render_digest_html(repository, digest)
    text = _render_digest_text(repository, digest)

    return _send_email(to_email, subject, text, html)


def _render_digest_html(repository: str, digest: dict[str, Any]) -> str:
    new_alerts = len(digest.get("new_alerts", []))
    health_trend = digest.get("health_trend")
    recommendations = digest.get("recommendations", [])
    dep_updates = digest.get("dependency_updates", [])

    trend_html = ""
    if health_trend is not None:
        emoji = "ðŸŸ¢" if health_trend >= 0 else "ðŸ”´"
        direction = "improved" if health_trend >= 0 else "declined"
        trend_html = f"<p>Health score {direction} by <strong>{abs(health_trend)}</strong> points.</p>"

    recs_html = ""
    if recommendations:
        recs_html = "<ul>" + "".join(f"<li>{r}</li>" for r in recommendations) + "</ul>"

    deps_html = ""
    if dep_updates:
        for d in dep_updates[:10]:
            deps_html += f"<li>{d.get('package', '?')}: {d.get('old_version', '?')} â†’ {d.get('new_version', '?')}</li>"
        deps_html = f"<ul>{deps_html}</ul>" if deps_html else ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body {{ font-family: -apple-system, system-ui, sans-serif; background: #0f1113; color: #f4f6f8; padding: 24px; }}
  .card {{ background: #1c1f22; border-radius: 12px; padding: 20px; margin-bottom: 16px; border: 1px solid rgba(255,255,255,0.1); }}
  h1, h2 {{ margin: 0 0 12px 0; }}
  .score {{ font-size: 32px; font-weight: 700; color: #42d6a4; }}
  .alert {{ color: #f97066; }}
  .muted {{ color: #a8b0b8; }}
  a {{ color: #42d6a4; }}
</style></head>
<body>
  <h1>RepoHeal Weekly Digest</h1>
  <p class="muted">{repository}</p>
  <div class="card">
    <h2>Health Summary</h2>
    {trend_html}
    <p>New alerts this week: <strong class="{'alert' if new_alerts > 0 else ''}">{new_alerts}</strong></p>
  </div>
  {f'<div class="card"><h2>Recommendations</h2>{recs_html}</div>' if recommendations else ''}
  {f'<div class="card"><h2>Dependency Updates</h2>{deps_html}</div>' if deps_html else ''}
  <p class="muted" style="margin-top: 24px;">Generated by RepoHeal</p>
</body></html>"""


def _render_digest_text(repository: str, digest: dict[str, Any]) -> str:
    new_alerts = len(digest.get("new_alerts", []))
    health_trend = digest.get("health_trend")
    recommendations = digest.get("recommendations", [])

    lines = [f"RepoHeal Weekly Digest â€” {repository}", "=" * 40, ""]
    if health_trend is not None:
        direction = "improved" if health_trend >= 0 else "declined"
        lines.append(f"Health score {direction} by {abs(health_trend)} points.")
    lines.append(f"New alerts this week: {new_alerts}")
    if recommendations:
        lines.extend(["", "Recommendations:"] + [f"  - {r}" for r in recommendations])
    lines.extend(["", "Generated by RepoHeal"])
    return "\n".join(lines)


def _send_email(to_email: str, subject: str, text: str, html: str) -> bool:
    try:
        api_key = settings.RESEND_API_KEY
        if not api_key:
            logger.error("Failed to send digest email: RESEND_API_KEY is not set.")
            return False

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "from": settings.EMAIL_FROM,
            "to": [to_email],
            "subject": subject,
            "text": text,
            "html": html
        }

        # Use httpx to send a POST request to Resend API
        response = httpx.post(
            "https://api.resend.com/emails",
            headers=headers,
            json=payload,
            timeout=10.0
        )

        if response.status_code in (200, 201):
            logger.info(f"Digest email sent to {to_email} for subject '{subject}'")
            return True
        else:
            logger.error(f"Failed to send digest email. Resend API returned {response.status_code}: {response.text}")
            return False
            
    except Exception as e:
        logger.error(f"Failed to send digest email: {e}")
        return False
