from typing import Any, Dict, List, Optional

from app.models.migration_models import HealthReport, SymbolAssessment
from app.utils.logger import get_logger

logger = get_logger(__name__)

SHIM_HEADER = '''"""
repoheal_fixes.py — Auto-generated compatibility shims for deprecated/removed APIs.
Generated by RepoHeal.
"""
'''

SHIM_TEMPLATES: Dict[str, str] = {
    "pandas.DataFrame.append": '''def repohealauto_append(df, other, ignore_index=False, **kwargs):
    """Compatibility shim: pandas.DataFrame.append -> pandas.concat.
    `append` is deprecated since pandas 1.4.0. This shim preserves old-code behavior.
    """
    import pandas as pd
    return pd.concat([df, other], ignore_index=ignore_index, **kwargs)
''',
    "pandas.Series.append": '''def repohealauto_append(series, other, ignore_index=False, **kwargs):
    """Compatibility shim: pandas.Series.append -> pandas.concat."""
    import pandas as pd
    return pd.concat([series, other], ignore_index=ignore_index, **kwargs)
''',
    "numpy.asscalar": '''def repohealauto_asscalar(a):
    """Compatibility shim: numpy.asscalar -> a.item().
    `asscalar` was removed in numpy 2.0. This shim preserves old-code behavior.
    """
    return a.item()
''',
    "sklearn.cross_validation": '''# Compatibility shim: sklearn.cross_validation -> sklearn.model_selection
from sklearn.model_selection import *  # noqa: F401, F403
''',
    "sklearn.grid_search": '''# Compatibility shim: sklearn.grid_search -> sklearn.model_selection
from sklearn.model_selection import *  # noqa: F401, F403
''',
}


def _extract_shim(assessment: SymbolAssessment, analysis: Dict[str, Any]) -> Optional[str]:
    """Build a compatibility shim for a deprecated/removed symbol."""
    symbol = assessment.symbol

    if not assessment.relationships:
        return None

    has_replacement = any(r.relation == "deprecated_in_favor_of" for r in assessment.relationships)
    is_removed = any(r.relation == "removed_in" for r in assessment.relationships)

    # Use template if available (preferred)
    template = SHIM_TEMPLATES.get(symbol)
    if template and (has_replacement or is_removed):
        return template

    # Try to build a shim from relationships
    replacement = None
    for r in assessment.relationships:
        if r.relation == "deprecated_in_favor_of" and r.target:
            replacement = r.target
            break

    if not replacement:
        return None

    method_name = symbol.split(".")[-1]
    lib = assessment.library
    return None  # Unknown patterns require manual review


def generate_shims(report: HealthReport, analysis: Dict[str, Any]) -> str:
    """Generate a repoheal_fixes.py file with shims for all deprecated/removed APIs."""
    shims: List[str] = [SHIM_HEADER]
    generated = 0
    manual_needed = 0

    for dep in getattr(report, "deprecated_apis", []):
        shim = _extract_shim(dep, analysis)
        if shim:
            shims.append(shim)
            generated += 1
        else:
            manual_needed += 1

    if generated == 0 and manual_needed == 0:
        return ""

    footer = f"\n# {generated} shim(s) generated, {manual_needed} require(s) manual review.\n"
    shims.append(footer)
    content = "\n".join(shims)

    if generated:
        logger.info("Generated %d compatibility shim(s), %d manual", generated, manual_needed)

    return content
