import ast
import py_compile
import tempfile
import io
from typing import Any, Dict, List, Optional, Tuple

from app.models.migration_models import HealthReport, SymbolAssessment
from app.utils.logger import get_logger

logger = get_logger(__name__)

SHIM_HEADER = '''"""
repoheal_fixes.py — Auto-generated compatibility shims for deprecated/removed APIs.
Generated by RepoHeal.

Import in your code and replace deprecated calls with repohealauto_* equivalents.
"""
'''

SHIM_TEMPLATES: Dict[str, str] = {
    "pandas.DataFrame.append": '''def repohealauto_append(df, other, ignore_index=False, **kwargs):
    """Compatibility shim: pandas.DataFrame.append -> pandas.concat."""
    import pandas as pd
    return pd.concat([df, other], ignore_index=ignore_index, **kwargs)
''',
    "pandas.Series.append": '''def repohealauto_append(series, other, ignore_index=False, **kwargs):
    """Compatibility shim: pandas.Series.append -> pandas.concat."""
    import pandas as pd
    return pd.concat([series, other], ignore_index=ignore_index, **kwargs)
''',
    "numpy.asscalar": '''def repohealauto_asscalar(a):
    """Compatibility shim: numpy.asscalar -> a.item()."""
    return a.item()
''',
    "sklearn.cross_validation": '''# Compatibility shim: sklearn.cross_validation -> sklearn.model_selection
from sklearn.model_selection import *  # noqa: F401, F403
''',
    "sklearn.grid_search": '''# Compatibility shim: sklearn.grid_search -> sklearn.model_selection
from sklearn.model_selection import *  # noqa: F401, F403
''',
}


def _symbol_to_import_path(symbol: str) -> Tuple[str, str]:
    """Convert 'pandas.DataFrame.append' -> ('pandas', 'pandas.DataFrame.append')."""
    parts = symbol.split(".")
    if len(parts) < 2:
        return (symbol, symbol)
    return (parts[0], ".".join(parts))


def _build_forwarding_shim(symbol: str, library: str) -> str:
    """
    Generate a repohealauto_* forwarding function for a deprecated API
    that has NO known replacement.  The shim delegates to the original
    deprecated function so existing code continues to work.
    """
    parts = symbol.split(".")
    func_name = parts[-1]
    lib_root = parts[0]
    import_path = ".".join(parts)

    safe_name = func_name.replace(".", "_").replace("-", "_")
    guard = f"_repoheal_{safe_name}_imported"

    return f'''try:
    {guard}
except NameError:
    import {lib_root} as _repoheal_{lib_root}
    {guard} = True

def repohealauto_{safe_name}(*args, **kwargs):
    """Compatibility shim: {symbol} — forwards to original {symbol}.
    This API is deprecated. The shim preserves old-code behavior.
    Replace calls to '{func_name}()' with 'repohealauto_{safe_name}()'.
    """
    return _repoheal_{lib_root}.{import_path[len(lib_root)+1:]}(*args, **kwargs)
'''


def _extract_shim(assessment: SymbolAssessment, analysis: Dict[str, Any]) -> Optional[str]:
    symbol = assessment.symbol
    template = SHIM_TEMPLATES.get(symbol)
    if template:
        return template

    has_replacement = any(r.relation == "deprecated_in_favor_of" for r in (assessment.relationships or []))
    if has_replacement:
        for r in (assessment.relationships or []):
            if r.relation == "deprecated_in_favor_of" and r.target:
                method_name = symbol.split(".")[-1]
                lib = assessment.library or symbol.split(".")[0]
                return None  # Has a known replacement; defer to AST/LLM patching

    # No replacement known — generate a forwarding shim
    lib = assessment.library or symbol.split(".")[0]
    return _build_forwarding_shim(symbol, lib)


def generate_shims(report: HealthReport, analysis: Dict[str, Any]) -> str:
    shims: List[str] = [SHIM_HEADER]
    generated = 0
    manual_needed = 0

    for dep in getattr(report, "deprecated_apis", []):
        shim = _extract_shim(dep, analysis)
        if shim:
            shims.append(shim)
            generated += 1

    if generated == 0:
        return ""

    footer = f"\n# {generated} shim(s) generated.\n"
    shims.append(footer)
    content = "\n".join(shims)

    logger.info("Generated %d compatibility shim(s)", generated)
    return content


# ── Compilation check ──────────────────────────────────────────────────────

def check_compilation(source_code: str, filename: str = "check.py") -> Tuple[bool, Optional[str]]:
    """Return (compiles_ok, error_message) for the given Python source."""
    try:
        ast.parse(source_code)
    except SyntaxError as e:
        return False, f"SyntaxError: {e}"

    try:
        compile(source_code, filename, "exec")
    except SyntaxError as e:
        return False, f"CompileError: {e}"
    except ValueError as e:
        return False, f"ValueError: {e}"

    return True, None


def check_files_compilation(file_map: Dict[str, str]) -> Dict[str, Tuple[bool, Optional[str]]]:
    """Check compilation for multiple files. Returns {path: (ok, error)}."""
    results = {}
    for path, source in file_map.items():
        results[path] = check_compilation(source, filename=path)
    return results


# ── Tiered patch-retry with Groq ───────────────────────────────────────────

async def tiered_patch_with_retry(
    original_code: str,
    symbol: str,
    library: str,
    replacement: Optional[str],
    llm_provider,
    max_groq_attempts: int = 3,
) -> Tuple[Optional[str], str]:
    """
    Patch source code for a deprecated symbol using a tiered approach:
    1. Try AST-based transform (RemediationEngine) -> compile check.
    2. If AST fails, try Groq up to max_groq_attempts -> compile check each time.
    3. If all fail, return (None, reason).

    Returns (patched_code_or_None, status_label) where status_label is one of:
      "auto_merge"   — compiles after AST patch
      "draft_pr"     — compiles after Groq patch (human should review)
      "human_review" — all attempts failed
    """
    # ── Tier 1: AST transform ──────────────────────────────────────────
    from app.remediation.engine import RemediationEngine

    engine = RemediationEngine(original_code)
    modified = False

    if replacement:
        parts = symbol.split(".")
        if len(parts) >= 2:
            engine.rewrite_import(parts[0], parts[0])
        engine.rename_symbol(symbol, replacement) if "." in replacement else None
        engine.rename_symbol(symbol.split(".")[-1], replacement)
        if engine.validate():
            modified_code = engine.get_modified_source()
            if modified_code != original_code:
                ok, err = check_compilation(modified_code)
                if ok:
                    return modified_code, "auto_merge"

    # ── Tier 2: Groq with retry ─────────────────────────────────────────
    if llm_provider:
        from app.llm.patch_generator import MIGRATION_PROMPT_TEMPLATE

        for attempt in range(1, max_groq_attempts + 1):
            prompt = MIGRATION_PROMPT_TEMPLATE.format(
                library=library,
                current_version="unknown",
                target_version="unknown",
                symbol=symbol,
                replacement=replacement or "unknown",
                affected_code=f"```python\n{original_code}\n```",
            )
            try:
                raw = await llm_provider.generate(prompt, max_tokens=4096)
                import json, re
                match = re.search(r'"modified_code"\s*:\s*"(.+?)"', raw, re.DOTALL)
                if match:
                    candidate = match.group(1).replace("\\n", "\n").replace('\\"', '"')
                else:
                    code_match = re.search(r'```python\n(.*?)\n```', raw, re.DOTALL)
                    candidate = code_match.group(1) if code_match else raw

                ok, err = check_compilation(candidate)
                if ok and candidate.strip() != original_code.strip():
                    return candidate, "draft_pr"
                logger.warning(f"Groq attempt {attempt}/{max_groq_attempts} failed: {err}")
            except Exception as e:
                logger.warning(f"Groq attempt {attempt}/{max_groq_attempts} error: {e}")

    return None, "human_review"
