from typing import Any
from app.github.client import RepoHealGitHubClient
from app.models.migration_models import HealthReport
from app.utils.logger import get_logger

logger = get_logger(__name__)

class ChangesBranchManager:
    BRANCH_PREFIX = "repoheal.changes"
    
    def __init__(self, github_client: RepoHealGitHubClient):
        self.client = github_client
    
    def create_changes_branch(self, repo, plan_name: str) -> str:
        """Create branch from default branch for code changes"""
        branch_name = f"{self.BRANCH_PREFIX}.{plan_name}"
        self.client.create_branch(repo, branch_name)
        return branch_name
    
    def commit_change(self, repo, branch_name: str, file_path: str, content: str, message: str) -> None:
        self.client.upsert_file(repo, branch_name, file_path, content, message)
        
    def batch_commit_changes(self, repo, branch_name: str, files: dict, message: str) -> None:
        try:
            self.client.batch_upsert_files(repo, branch_name, files, message)
        except Exception as e:
            logger.error(f"Failed to batch commit changes, falling back to sequential: {e}")
            for path, content in files.items():
                self.commit_change(repo, branch_name, path, content, message)
    
    def create_migration_pr(self, repo, branch_name: str, health_report: HealthReport) -> Any:
        title = f"[RepoHeal] Migration: {branch_name.replace(self.BRANCH_PREFIX + '.', '')}"
        body = self._generate_pr_body(health_report)
        return self.client.create_pull_request(repo, branch_name, title, body)
        
    def _generate_pr_body(self, report: HealthReport) -> str:
        return f"## RepoHeal Migration\n\nThis PR was generated by RepoHeal to address dependency risks.\n\n- **Health Score**: {report.overall_health_score}/100\n- **Risk Level**: {report.overall_risk_level.upper()}\n\nSee the migration document in the `repoheal.meta` branch for full details."
